import "./globals.css";

import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";
import { ProductoProvider } from "./components/contex/contex";

export const metadata = {
  title: "Ofertas-Ya",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.io" />
      </head>
      <body
        className={``}
      >
        <ProductoProvider>
          <Navbar />
          {children}
          <Footer />
        </ProductoProvider>
      </body>
    </html>
  );
}
